// Beautiful Bali sample data used as fallback when Sanity is empty.
// Once you add real activities in /studio, they will replace these automatically.

export const sampleCategories = [
  { _id: 'cat-1', title: 'Adventure', slug: { current: 'adventure' } },
  { _id: 'cat-2', title: 'Cultural', slug: { current: 'cultural' } },
  { _id: 'cat-3', title: 'Nature', slug: { current: 'nature' } },
  { _id: 'cat-4', title: 'Beach & Island', slug: { current: 'beach-island' } },
  { _id: 'cat-5', title: 'Wellness', slug: { current: 'wellness' } },
]

const makeImg = (url) => ({ url, alt: '' })

export const sampleActivities = [
  {
    _id: 'act-1',
    title: 'Mount Batur Sunrise Trekking',
    slug: { current: 'mount-batur-sunrise-trekking' },
    shortDescription: 'Hike an active volcano in the dark and watch the sun rise above the clouds with hot coffee in hand.',
    fullDescription: 'Begin your adventure at 2:00 AM with a pickup from your hotel. After a 1.5-hour drive, meet your local English-speaking guide at the base of Mount Batur. The 2-hour ascent under starlight rewards you with one of the most spectacular sunrises in Southeast Asia — a horizon of fire above Lake Batur and Mount Agung. Enjoy a hot breakfast cooked using the volcano\'s natural steam, then descend through lava fields before returning to your hotel by lunchtime.',
    category: { _id: 'cat-1', title: 'Adventure', slug: { current: 'adventure' } },
    price: 45,
    duration: '8 hours',
    location: 'Kintamani, Bangli',
    featured: true,
    coverImage: makeImg('https://images.unsplash.com/photo-1557093793-e196ae071479?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1557093793-e196ae071479?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1628698240719-195c74672c45?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1557093793-d149a38a1be8?w=1600&q=80'),
    ],
    highlights: ['Sunrise from 1,717m summit', 'Volcano-steamed breakfast', 'Hotel pickup & drop-off', 'Professional local guide', 'Flashlight provided'],
    included: ['Hotel transfer (round trip)', 'English-speaking guide', 'Trekking flashlight', 'Light breakfast', 'Mineral water', 'Insurance'],
    excluded: ['Personal expenses', 'Trekking pole rental ($3)', 'Tips for guide'],
  },
  {
    _id: 'act-2',
    title: 'Nusa Penida Island Full Day Tour',
    slug: { current: 'nusa-penida-island-full-day-tour' },
    shortDescription: 'Sail to the dramatic island of Nusa Penida and discover Kelingking Beach, Angel\'s Billabong, and Broken Beach in one unforgettable day.',
    fullDescription: 'Cross the turquoise Badung Strait by speedboat to reach Nusa Penida — Bali\'s wilder, untamed sister island. Your private driver and guide take you to the four most iconic viewpoints: T-Rex shaped Kelingking Beach, the natural infinity pool of Angel\'s Billabong, the cliff-arch of Broken Beach, and the secluded Crystal Bay where you can swim in pristine waters.',
    category: { _id: 'cat-4', title: 'Beach & Island', slug: { current: 'beach-island' } },
    price: 75,
    duration: '12 hours',
    location: 'Nusa Penida',
    featured: true,
    coverImage: makeImg('https://images.unsplash.com/photo-1555400038-a088c772c8cd?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1555400038-a088c772c8cd?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1544644181-af0e1e14916f?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1654703942329-01d6a0a3ed62?w=1600&q=80'),
    ],
    highlights: ['Kelingking Beach viewpoint', 'Angel\'s Billabong natural pool', 'Broken Beach', 'Crystal Bay swim & snorkel', 'Speedboat return transfer'],
    included: ['Hotel pickup in South Bali', 'Round-trip speedboat ticket', 'Private car & driver on the island', 'English-speaking guide', 'Lunch at local warung', 'Mineral water'],
    excluded: ['Snorkel gear rental', 'Personal expenses', 'Tips'],
  },
  {
    _id: 'act-3',
    title: 'Ubud Cultural & Rice Terrace Tour',
    slug: { current: 'ubud-cultural-rice-terrace-tour' },
    shortDescription: 'Walk through the UNESCO Tegalalang rice terraces, visit a sacred water temple, and watch a traditional Legong dance in Ubud.',
    fullDescription: 'Begin at the magical Tegalalang Rice Terraces, where centuries-old subak irrigation creates a living green sculpture. Continue to Tirta Empul, a sacred spring temple where Balinese have purified themselves for over a thousand years. After a traditional Balinese lunch, explore Ubud\'s art market and the Sacred Monkey Forest. End your day with a mesmerizing Legong dance performance set to live gamelan music.',
    category: { _id: 'cat-2', title: 'Cultural', slug: { current: 'cultural' } },
    price: 55,
    duration: '10 hours',
    location: 'Ubud, Gianyar',
    featured: true,
    coverImage: makeImg('https://images.unsplash.com/photo-1523539693385-e5e891eb4465?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1523539693385-e5e891eb4465?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1576475706812-822620fc23ba?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1572908721147-0a9eb395762d?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1656247203824-3d6f99461ba4?w=1600&q=80'),
    ],
    highlights: ['Tegalalang Rice Terraces', 'Tirta Empul holy water temple', 'Sacred Monkey Forest', 'Traditional Legong dance', 'Balinese lunch included'],
    included: ['Air-conditioned private car', 'English-speaking guide', 'All entrance fees', 'Balinese lunch', 'Dance show ticket', 'Bottled water'],
    excluded: ['Sarong rental ($1)', 'Personal shopping', 'Tips'],
  },
  {
    _id: 'act-4',
    title: 'Sekumpul & Banyumala Waterfalls',
    slug: { current: 'sekumpul-banyumala-waterfalls' },
    shortDescription: 'Trek through the jungle of North Bali to two of the island\'s most breathtaking hidden waterfalls.',
    fullDescription: 'Drive 2 hours north to Sekumpul — voted the most beautiful waterfall in Bali. A 30-minute jungle trek leads you down to its 80-meter twin cascades. After a swim and lunch with a local family, visit Banyumala Twin Waterfalls, a serene jungle oasis perfect for cooling off in crystal pools.',
    category: { _id: 'cat-3', title: 'Nature', slug: { current: 'nature' } },
    price: 65,
    duration: '11 hours',
    location: 'Sekumpul, Buleleng',
    featured: false,
    coverImage: makeImg('https://images.unsplash.com/photo-1628698240719-195c74672c45?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1628698240719-195c74672c45?w=1600&q=80'),
      makeImg('https://images.unsplash.com/photo-1557093793-d149a38a1be8?w=1600&q=80'),
    ],
    highlights: ['Sekumpul twin waterfalls', 'Banyumala swimming pools', 'Authentic village lunch', 'Local guide & trekking'],
    included: ['Private transport', 'English guide', 'Entrance & local guide fees', 'Lunch', 'Water'],
    excluded: ['Tips', 'Extra activities'],
  },
  {
    _id: 'act-5',
    title: 'Pura Ulun Danu Bratan & Bedugul',
    slug: { current: 'pura-ulun-danu-bratan-bedugul' },
    shortDescription: 'Visit the iconic lake temple floating on Lake Bratan, plus the colorful Handara Gate and Jatiluwih heritage rice fields.',
    fullDescription: 'Escape to the cool mountains of Bedugul. Photograph the legendary Pura Ulun Danu Bratan — the temple that seems to float on the lake. Continue to the iconic Handara Gate and finish at Jatiluwih, a UNESCO World Heritage rice terrace landscape.',
    category: { _id: 'cat-2', title: 'Cultural', slug: { current: 'cultural' } },
    price: 50,
    duration: '9 hours',
    location: 'Bedugul, Tabanan',
    featured: true,
    coverImage: makeImg('https://images.unsplash.com/photo-1590476490372-b996670ee862?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1590476490372-b996670ee862?w=1600&q=80'),
      makeImg('https://images.pexels.com/photos/8333127/pexels-photo-8333127.jpeg?w=1600'),
      makeImg('https://images.unsplash.com/photo-1599117372663-d68b2e2189d7?w=1600&q=80'),
    ],
    highlights: ['Pura Ulun Danu Bratan temple', 'Handara Gate photo stop', 'Jatiluwih UNESCO rice terraces', 'Strawberry farm visit'],
    included: ['Private AC car', 'Driver-guide', 'Entrance fees', 'Mineral water'],
    excluded: ['Lunch', 'Tips', 'Personal expenses'],
  },
  {
    _id: 'act-6',
    title: 'Balinese Cooking Class in Ubud',
    slug: { current: 'balinese-cooking-class-ubud' },
    shortDescription: 'Learn to cook 6 authentic Balinese dishes after a guided morning market tour and visit to an organic rice paddy.',
    fullDescription: 'Start with a tour of a colorful local market, where your chef explains every spice and herb. Visit a rice paddy to understand the foundation of Balinese cuisine, then return to a traditional open-air kitchen to prepare and feast on six authentic dishes including Nasi Kuning, Sate Lilit, and Black Rice Pudding.',
    category: { _id: 'cat-2', title: 'Cultural', slug: { current: 'cultural' } },
    price: 40,
    duration: '5 hours',
    location: 'Ubud, Gianyar',
    featured: false,
    coverImage: makeImg('https://images.pexels.com/photos/7148943/pexels-photo-7148943.jpeg?w=1600'),
    galleryImages: [makeImg('https://images.pexels.com/photos/7148943/pexels-photo-7148943.jpeg?w=1600')],
    highlights: ['Morning market tour', 'Rice paddy visit', 'Cook 6 authentic dishes', 'Recipe booklet to take home'],
    included: ['Hotel pickup (Ubud area)', 'All ingredients', 'Apron & recipes', 'Lunch (your dishes)'],
    excluded: ['Pickup outside Ubud (+$10)', 'Tips'],
  },
  {
    _id: 'act-7',
    title: 'Bali Swing & Jungle Adventure',
    slug: { current: 'bali-swing-jungle-adventure' },
    shortDescription: 'Fly over the jungle on Bali\'s most famous swings with stunning rice valley views.',
    fullDescription: 'A perfect half-day of fun. Visit a curated swing park with 7 different swings of varying heights, photo nests, and instagram-famous gates — all overlooking emerald jungle and rice terraces. Safety harnesses, professional photographers, and complimentary drinks included.',
    category: { _id: 'cat-1', title: 'Adventure', slug: { current: 'adventure' } },
    price: 35,
    duration: '4 hours',
    location: 'Tegalalang, Ubud',
    featured: false,
    coverImage: makeImg('https://images.unsplash.com/photo-1576475706812-822620fc23ba?w=1600&q=80'),
    galleryImages: [makeImg('https://images.unsplash.com/photo-1576475706812-822620fc23ba?w=1600&q=80')],
    highlights: ['7 jungle swings', 'Photo nests & bird cages', 'Safety harness included', 'Welcome drink'],
    included: ['Entrance & all swings', 'Safety equipment', 'Welcome drink', 'Hotel transfer (South Bali)'],
    excluded: ['Photo package upgrade', 'Tips'],
  },
  {
    _id: 'act-8',
    title: 'Uluwatu Temple & Kecak Fire Dance',
    slug: { current: 'uluwatu-temple-kecak-fire-dance' },
    shortDescription: 'Watch the sunset behind a cliff-top temple followed by the hypnotic Kecak fire dance and a seafood dinner on Jimbaran beach.',
    fullDescription: 'Perched on a 70-meter cliff above the Indian Ocean, Pura Luhur Uluwatu is one of Bali\'s most sacred sea temples. Arrive in time to wander the temple grounds, then settle into the open-air amphitheater for the legendary Kecak Fire Dance performed by 70 men chanting under the stars. Finish with grilled seafood, your feet in the sand at Jimbaran Bay.',
    category: { _id: 'cat-2', title: 'Cultural', slug: { current: 'cultural' } },
    price: 60,
    duration: '7 hours',
    location: 'Uluwatu, Badung',
    featured: true,
    coverImage: makeImg('https://images.unsplash.com/photo-1599117372663-d68b2e2189d7?w=1600&q=80'),
    galleryImages: [
      makeImg('https://images.unsplash.com/photo-1599117372663-d68b2e2189d7?w=1600&q=80'),
      makeImg('https://images.pexels.com/photos/8333127/pexels-photo-8333127.jpeg?w=1600'),
    ],
    highlights: ['Cliff-top temple at sunset', 'Kecak fire dance', 'Jimbaran seafood dinner', 'Sarong provided'],
    included: ['Private AC car', 'Driver-guide', 'Temple entrance', 'Kecak dance ticket', 'Sarong rental'],
    excluded: ['Seafood dinner (~$15-25)', 'Tips'],
  },
]

export const sampleTestimonials = [
  {
    _id: 't-1',
    customerName: 'Sarah Mitchell',
    country: 'Australia',
    review: 'The Mount Batur sunrise trek was the highlight of our Bali trip. Our guide Wayan was incredible — patient, funny, and the breakfast on the volcano was unforgettable.',
    rating: 5,
    avatar: { url: 'https://i.pravatar.cc/200?img=47' },
  },
  {
    _id: 't-2',
    customerName: 'James & Emma Thompson',
    country: 'United Kingdom',
    review: 'Kayasa organized everything perfectly via WhatsApp. Easy, fast, and the Nusa Penida tour was beyond our expectations. Felt like having a local friend in Bali.',
    rating: 5,
    avatar: { url: 'https://i.pravatar.cc/200?img=12' },
  },
  {
    _id: 't-3',
    customerName: 'Sophie Laurent',
    country: 'France',
    review: 'The Ubud cultural tour gave me a real connection with Bali — not just the typical tourist photos. The rice terraces at golden hour... magical.',
    rating: 5,
    avatar: { url: 'https://i.pravatar.cc/200?img=45' },
  },
  {
    _id: 't-4',
    customerName: 'Daniel Kim',
    country: 'South Korea',
    review: 'Booked three different tours through Kayasa. Each driver was professional, the cars spotless, and they always brought us water and snacks. 10/10.',
    rating: 5,
    avatar: { url: 'https://i.pravatar.cc/200?img=33' },
  },
]

export const sampleSiteSettings = {
  companyName: 'Kayasa Bali Tour',
  companyDescription: 'Authentic, hand-crafted Bali experiences led by passionate local guides. From sunrise volcano treks to sacred temple ceremonies, we make Bali unforgettable.',
  whatsappNumber: '6281237656995',
  email: 'hello@kayasabalitour.com',
  address: 'Jl. Raya Ubud No. 88, Gianyar, Bali 80571',
  instagram: 'https://instagram.com/kayasabalitour',
  facebook: 'https://facebook.com/kayasabalitour',
}
